<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>dwaslashe-Lobby</name>
    <description>Lobby</description>

    <groupId>xyz.dwaslashe</groupId>
    <artifactId>dwaslashe-Lobby</artifactId>
    <version>1.0-stable</version>

    <repositories>
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>okaeri-repo</id>
            <url>https://storehouse.okaeri.eu/repository/maven-public/</url>
        </repository>
        <repository>
            <id>krypton</id>
            <url>https://repo.kryptonmc.org/releases</url>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <!-- This is a temporary reference as the Maven Shade plugin
                that supports Java 16 is not released yet -->
            <id>maven-snapshots</id>
            <url>https://repository.apache.org/content/repositories/snapshots/</url>
        </pluginRepository>
        <pluginRepository>
            <id>krypton</id>
            <url>https://repo.kryptonmc.org/releases</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot</artifactId>
            <version>1.18-R0.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/Desktop/Projekty Intellij/dwaslashe-Lobby/libs/spigot-1.16.5 (1).jar</systemPath>
        </dependency>
        <dependency>
            <groupId>org.placeholder</groupId>
            <artifactId>spigot</artifactId>
            <version>1.18-R0.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/Desktop/Projekty Intellij/dwaslashe-Lobby/libs/PlaceholderAPI-2.11.1 (1).jar</systemPath>
        </dependency>
        <dependency>
            <groupId>xyz.arturek</groupId>
            <artifactId>mineLogin</artifactId>
            <version>1.18-R0.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>C:/Users/ciapc/Desktop/Projekty Intellij/dwaslashe-Lobby/libs/mineLogin-1.5.4-bungeecord-public (1).jar</systemPath>
        </dependency>
        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-pluralize</artifactId>
            <version>1.1.1</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-configs-yaml-bukkit</artifactId>
            <version>3.4.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>me.neznamy</groupId>
            <artifactId>tab-api</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>eu.okaeri</groupId>
            <artifactId>okaeri-configs-yaml-snakeyaml</artifactId>
            <version>3.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
            <version>1.7</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.22</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.luckperms</groupId>
            <artifactId>api</artifactId>
            <version>5.0</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.3.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <dependencyReducedPomLocation>
                                ${project.build.directory}/dependency-reduced-pom.xml
                            </dependencyReducedPomLocation>
                            <relocations>
                                <relocation>
                                    <pattern>eu.okaeri.configs</pattern>
                                    <shadedPattern>xyz.dwaslashe.libs.eu.okaeri.configs</shadedPattern>
                                </relocation>
                                <relocation>
                                    <pattern>eu.okaeri.pluralize</pattern>
                                    <shadedPattern>xyz.dwaslashe.libs.eu.okaeri.pluralize</shadedPattern>
                                </relocation>
                            </relocations>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

</project>